name = "cheatess"
version = "0.1.0"
description = "Real time cheating never was so easy"
authors = ["Dawid Sielużycki <@Leghart>"]
readme = "README.md"
license = "MIT"


[tool.ruff]
line-length = 119
target-version = "py312"

[tool.ruff.lint]
extend-select = ["I", "S", "RUF"]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101", "S105", "S106", "S108", "S603", "S607"]

[tool.mypy]
strict = true

pretty = true
show_error_context = true
show_column_numbers = true
warn_return_any = true
warn_redundant_casts = true
warn_unreachable = true
warn_unused_ignores = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true

enable_error_code = [
    "explicit-override",
    "ignore-without-code",
    "narrowed-type-not-subtype",
    "truthy-bool",
]

