FROM rust:slim as builder

RUN apt-get update && apt-get install -y \
    pkg-config \
    libwayland-dev \
    libpipewire-0.3-dev \
    libclang-dev \
    libegl-dev \
    libopencv-dev \
    libgbm-dev \
    clang \
    llvm-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN rustup component add rustfmt clippy

COPY core/src /workspace/src
COPY core/templates /workspace/templates
COPY core/Cargo.* /workspace

WORKDIR /workspace

RUN cargo test --no-run

FROM rust:slim

RUN apt-get update && apt-get install -y \
    pkg-config \
    libwayland-dev \
    libpipewire-0.3-dev \
    libclang-dev \
    libegl-dev \
    libopencv-dev \
    libgbm-dev \
    clang \
    llvm-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN rustup component add rustfmt clippy

WORKDIR /workspace

COPY --from=builder /workspace /workspace
COPY --from=builder /workspace/target /workspace/target
COPY --from=builder /usr/local/cargo /usr/local/cargo

CMD ["/bin/bash"]