[package]
name = "cheatess-core"
version = "0.1.0"
edition = "2021"

[dependencies]
device_query = "3.0.0"
image = "0.24.9"
opencv = "0.94.2"
rdev = "0.5.3"
screenshots = "0.8.10"
serde = {version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
zmq = "0.10.0"
subprocess = "0.2.9"
actix-web = "4"
actix-web-actors = "4"
futures-util = "0.3"
actix-ws = "0.3.0"

[dev-dependencies]
clippy = "0.0.302"
rstest = "0.24.0"
