[package]
name = "cheatess-core"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24.9"
opencv = { version = "0.94.2", features = ["clang-runtime"] }
subprocess = "0.2.9"
xcap = "0.6.1"

[dev-dependencies]
clippy = "0.0.302"
rstest = "0.24.0"
