on: [pull_request]

name: CI

jobs:
  prepare_image:
    name: Build Test Image
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    secrets:
      username:  ${{ secrets.DOCKERHUB_USERNAME }}
      token:  ${{ secrets.DOCKERHUB_TOKEN }} 

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ username }}
          password: ${{ token }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.test
          push: true
          tags: ${{ username }}/cheatess-test:latest

  check:
    name: Check
    runs-on: ubuntu-latest
    needs: prepare_image
    secrets:
      username:  ${{ secrets.DOCKERHUB_USERNAME }}    
    container:
      image: ${{ username }}/cheatess-test:latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Run cargo check
        run: cargo check
        working-directory: core

  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: prepare_image    
    secrets:
      username:  ${{ secrets.DOCKERHUB_USERNAME }}    
    container:
      image: ${{ username }}/cheatess-test:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run cargo test
        run: cargo test
        working-directory: core

  fmt:
    name: Format
    runs-on: ubuntu-latest
    needs: prepare_image    
    secrets:
      username:  ${{ secrets.DOCKERHUB_USERNAME }}    
    container:
      image: ${{ username }}/cheatess-test:latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Run cargo fmt
        run: cargo fmt --all -- --check
        working-directory: core

  clippy:
    name: Lint
    runs-on: ubuntu-latest
    needs: prepare_image    
    secrets:
      username:  ${{ secrets.DOCKERHUB_USERNAME }}    
    container:
      image: ${{ username }}/cheatess-test:latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Run cargo clippy
        run: cargo clippy -- -D warnings
        working-directory: core
