on: [pull_request]

name: CI

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/cheatess-test:latest

jobs:
  prepare_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check if Cargo files changed
        id: check_cargo
        run: |
          git fetch origin develop
          changed_files=$(git diff --name-only origin/develop...HEAD)
          echo "Changed files: $changed_files"
          echo "::set-output name=changed::$(echo $changed_files | grep -E 'Cargo.toml|Cargo.lock' || true)"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker if needed
        if: steps.check_cargo.outputs.changed != ''
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.test
          push: true
          tags: ${{ env.IMAGE_NAME }}

  check:
    name: Check
    runs-on: ubuntu-latest
    container:
      image: leghart/cheatess-test:latest
    needs: [prepare_image]
    steps:
      - uses: actions/checkout@v2
      - run: cargo check
        working-directory: core

  test:
    name: Tests
    runs-on: ubuntu-latest
    container:
      image: leghart/cheatess-test:latest
    needs: [prepare_image]
    steps:
      - uses: actions/checkout@v2
      - run: cargo test
        working-directory: core

  fmt:
    name: Format
    runs-on: ubuntu-latest
    container:
      image: leghart/cheatess-test:latest
    needs: [prepare_image]
    steps:
      - uses: actions/checkout@v2
      - run: cargo fmt --all -- --check
        working-directory: core

  clippy:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: leghart/cheatess-test:latest
    needs: [prepare_image]
    steps:
      - uses: actions/checkout@v2
      - run: cargo clippy -- -D warnings
        working-directory: core
