on: [pull_request]

name: CI

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/cheatess-test:latest

jobs:
  check-for-cargo-changes:
    name: Check Cargo Changes
    runs-on: ubuntu-latest
    outputs:
      should_build: ${{ steps.check.outputs.changed }}
    steps:
      - uses: actions/checkout@v2

      - id: check
        run: |
          if git diff --name-only origin/${{ github.base_ref }} | grep -E 'Cargo\.(toml|lock)'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  prepare_image:
    name: Build Test Image
    runs-on: ubuntu-latest
    needs: check-for-cargo-changes
    if: needs.check-for-cargo-changes.outputs.should_build == 'true'
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.test
          push: true
          tags: ${{ env.IMAGE_NAME }}

  check:
    name: Check
    runs-on: ubuntu-latest
    needs: [check-for-cargo-changes, prepare_image]
    container:
      image: leghart/cheatess-test:latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo check

  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: [check-for-cargo-changes, prepare_image]
    container:
      image: leghart/cheatess-test:latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo test

  fmt:
    name: Format
    runs-on: ubuntu-latest
    needs: [check-for-cargo-changes, prepare_image]
    container:
      image: leghart/cheatess-test:latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo fmt --all -- --check

  clippy:
    name: Lint
    runs-on: ubuntu-latest
    needs: [check-for-cargo-changes, prepare_image]
    container:
      image: leghart/cheatess-test:latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo clippy -- -D warnings
