on: [pull_request]

name: CI

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    container:
      image: leghart/cheatess:0.1.0

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Run cargo check
        run: cargo check
        working-directory: core

  test:
    name: Run test suite
    runs-on: ubuntu-latest
    container:
      image: leghart/cheatess:0.1.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run cargo test
        run: cargo test
        working-directory: core

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    container:
      image: leghart/cheatess:0.1.0

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Run cargo fmt
        run: cargo fmt --all -- --check
        working-directory: core

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    container:
      image: leghart/cheatess:0.1.0

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Run cargo clippy
        run: cargo clippy -- -D warnings
        working-directory: core
