on:
  push:
    tags:
      - "*"

jobs:
  publish_core_crate:
    name: Publish Core Crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to crates.io
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
