on:
  push:
    tags:
      - "*"

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/cheatess-core:latest

jobs:
  publish_core_crate:
    name: Publish Core Crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to crates.io
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

  publish_image_prod:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.prod
          push: true
          tags: ${{ env.IMAGE_NAME }}
